In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/G7762.csv'

df = pd.read_csv(file_path)

df = df.iloc[1:282, :]
df = df.iloc[1:, :]

print(df)



    Unnamed: 0 QEP121505 QEP121505.1 QEP121505.2 QEP121505.3 Unnamed: 5  \
2         0.00    12.844      12.528      12.778      12.473      0.016   
3         1.00    12.815      12.543      12.845      12.472      0.016   
4         2.00    12.791      12.558      12.754      12.473      0.016   
5         3.00    12.784      12.518      12.732      12.475      0.016   
6         4.00    12.784      12.482      12.706      12.476      0.016   
..         ...       ...         ...         ...         ...        ...   
277     275.00    12.911      12.476      12.573      12.603      0.017   
278     276.00    12.911      12.476      12.573      12.614      0.017   
279     277.00    12.911      12.476      12.573      12.604      0.017   
280     278.00    12.915      12.476      12.573      12.614      0.017   
281     279.00     12.91      12.476      12.573       1.443      0.017   

    Unnamed: 6 Unnamed: 7  
2        0.024     35.669  
3        0.025      36.09  
4        0.024 

In [ ]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))


Number of rows: 280
Number of columns: 8


In [ ]:
import pandas as pd

df_processed = df.iloc[:, 1:]

selected_values = df_processed.iloc[:, :4]

print(selected_values)


    QEP121505 QEP121505.1 QEP121505.2 QEP121505.3
2      12.844      12.528      12.778      12.473
3      12.815      12.543      12.845      12.472
4      12.791      12.558      12.754      12.473
5      12.784      12.518      12.732      12.475
6      12.784      12.482      12.706      12.476
..        ...         ...         ...         ...
277    12.911      12.476      12.573      12.603
278    12.911      12.476      12.573      12.614
279    12.911      12.476      12.573      12.604
280    12.915      12.476      12.573      12.614
281     12.91      12.476      12.573       1.443

[280 rows x 4 columns]


In [ ]:
import pandas as pd

df_processed = df.iloc[:, 1:]
selected_values = df_processed.iloc[:, :4]

# Convert columns to numeric
selected_values = selected_values.apply(pd.to_numeric)

# Subtract values row by row
differences = selected_values.diff().iloc[1:]

print(differences)

     QEP121505  QEP121505.1  QEP121505.2  QEP121505.3
3       -0.029        0.015        0.067       -0.001
4       -0.024        0.015       -0.091        0.001
5       -0.007       -0.040       -0.022        0.002
6        0.000       -0.036       -0.026        0.001
7        0.000       -0.007       -0.122        0.002
..         ...          ...          ...          ...
277      0.011        0.000        0.000       -0.003
278      0.000        0.000        0.000        0.011
279      0.000        0.000        0.000       -0.010
280      0.004        0.000        0.000        0.010
281     -0.005        0.000        0.000      -11.171

[279 rows x 4 columns]


In [ ]:
#tempolarise devices 1,2,3,4

import numpy as np

def temporalize(data, lookback):
    output_data = []
    for i in range(data.shape[1]):
        column = data[:, i]
        temp_column = []
        for j in range(lookback, len(column)):
            temp_column.append(column[j-lookback:j])
        output_data.append(temp_column)
    return output_data

lookback = 10
temporalized_data = temporalize(differences.values, lookback)

for i, column in enumerate(temporalized_data):
    print(f"Column {i+1}:")
    for j, step in enumerate(column):
        print(f"Step {j}: {step}")
    print()

Column 1:
Step 0: [-0.029 -0.024 -0.007  0.     0.     0.001  0.002 -0.003  0.004  0.002]
Step 1: [-0.024 -0.007  0.     0.     0.001  0.002 -0.003  0.004  0.002  0.005]
Step 2: [-0.007  0.     0.     0.001  0.002 -0.003  0.004  0.002  0.005  0.023]
Step 3: [ 0.     0.     0.001  0.002 -0.003  0.004  0.002  0.005  0.023  0.002]
Step 4: [ 0.     0.001  0.002 -0.003  0.004  0.002  0.005  0.023  0.002  0.005]
Step 5: [ 0.001  0.002 -0.003  0.004  0.002  0.005  0.023  0.002  0.005  0.001]
Step 6: [ 0.002 -0.003  0.004  0.002  0.005  0.023  0.002  0.005  0.001  0.001]
Step 7: [-0.003  0.004  0.002  0.005  0.023  0.002  0.005  0.001  0.001  0.   ]
Step 8: [0.004 0.002 0.005 0.023 0.002 0.005 0.001 0.001 0.    0.002]
Step 9: [ 0.002  0.005  0.023  0.002  0.005  0.001  0.001  0.     0.002 -0.001]
Step 10: [ 0.005  0.023  0.002  0.005  0.001  0.001  0.     0.002 -0.001  0.   ]
Step 11: [ 0.023  0.002  0.005  0.001  0.001  0.     0.002 -0.001  0.     0.022]
Step 12: [ 0.002  0.005  0.001  0.001 

In [ ]:
#STATS

import numpy as np
from scipy.stats import mode

def temporalize(data, lookback):
    output_data = []
    for i in range(data.shape[1]):
        column = data[:, i]
        column = column.astype(float)
        temp_column = []
        for j in range(lookback, len(column)):
            window = column[j-lookback:j]
            mean = np.mean(window)
            median = np.median(window)
            min_val = np.min(window)
            max_val = np.max(window)
            mode_result = mode(window)
            if isinstance(mode_result[0], np.ndarray):
                mode_val = mode_result[0][0]
            else:
                mode_val = mode_result[0]
            std = np.std(window)
            mad = np.mean(np.abs(window - np.mean(window)))
            mse = np.mean((window - np.mean(window))**2)
            abs_dev = np.mean(np.abs(window - np.mean(window)))
            mad_mean = np.mean(np.abs(window - np.median(window)))
            temp_column.append([mean, median, min_val, max_val, mode_val, std, mad, mse, abs_dev, mad_mean])
        output_data.append(temp_column)
    return output_data

lookback = 10
temporalized_data = temporalize(differences.values, lookback)

for i, column in enumerate(temporalized_data):
    print(f"Column {i+1}:")
    for j, stats in enumerate(column):
        print(f"Step {j}: {stats}")
    print()

Column 1:
Step 0: [-0.005400000000000027, 0.0, -0.028999999999999915, 0.0039999999999995595, 0.0, 0.010992724866928764, 0.00875999999999973, 0.00012083999999999403, 0.00875999999999973, 0.00719999999999974]
Step 1: [-0.0019999999999999575, 0.0004999999999997229, -0.023999999999999133, 0.005000000000000782, 0.0, 0.008024961059095288, 0.00559999999999981, 6.439999999999576e-05, 0.00559999999999981, 0.004799999999999827]
Step 2: [0.0026999999999999247, 0.0014999999999991687, -0.006999999999999673, 0.022999999999999687, 0.0, 0.007510659092250075, 0.004780000000000051, 5.640999999999872e-05, 0.004780000000000051, 0.004499999999999993]
Step 3: [0.0035999999999999587, 0.0019999999999997797, -0.0030000000000001137, 0.022999999999999687, 0.0, 0.006799999999999952, 0.00424000000000003, 4.623999999999935e-05, 0.00424000000000003, 0.003600000000000314]
Step 4: [0.004099999999999859, 0.002000000000000668, -0.0030000000000001137, 0.022999999999999687, 0.002000000000000668, 0.0066999999999999395, 0.0

In [ ]:
import pandas as pd

def label_columns(df, threshold=1.5):
    labeled_df = df.copy()
    for col in df.columns:
        col_values = df[col].astype(float)
        if (col_values < threshold).any():
            labeled_df[col] = col_values.apply(lambda x: 1)
        else:
            labeled_df[col] = col_values.apply(lambda x: 0)
    return labeled_df

# Assuming 'selected_values' is your original DataFrame
labeled_values = label_columns(selected_values.iloc[1:])
print(labeled_values)

     QEP121505  QEP121505.1  QEP121505.2  QEP121505.3
3            0            0            0            1
4            0            0            0            1
5            0            0            0            1
6            0            0            0            1
7            0            0            0            1
..         ...          ...          ...          ...
277          0            0            0            1
278          0            0            0            1
279          0            0            0            1
280          0            0            0            1
281          0            0            0            1

[279 rows x 4 columns]


In [ ]:
#Temporalize labels

import numpy as np
import pandas as pd

def temporalize(data, lookback):
    output_data = []
    for i in range(data.shape[1]):
        column = data[:, i]
        temp_column = []
        for j in range(lookback, len(column)):
            temp_column.append(column[j-lookback:j])
        output_data.append(temp_column)
    return output_data

labeled_values_array = labeled_values.values

lookback = 10

y_temp = temporalize(labeled_values_array, lookback)

for i, column in enumerate(y_temp):
    print(f"Column {i+1}:")
    for j, step in enumerate(column):
        print(f"Step {j}: {step}")
    print()


Column 1:
Step 0: [0 0 0 0 0 0 0 0 0 0]
Step 1: [0 0 0 0 0 0 0 0 0 0]
Step 2: [0 0 0 0 0 0 0 0 0 0]
Step 3: [0 0 0 0 0 0 0 0 0 0]
Step 4: [0 0 0 0 0 0 0 0 0 0]
Step 5: [0 0 0 0 0 0 0 0 0 0]
Step 6: [0 0 0 0 0 0 0 0 0 0]
Step 7: [0 0 0 0 0 0 0 0 0 0]
Step 8: [0 0 0 0 0 0 0 0 0 0]
Step 9: [0 0 0 0 0 0 0 0 0 0]
Step 10: [0 0 0 0 0 0 0 0 0 0]
Step 11: [0 0 0 0 0 0 0 0 0 0]
Step 12: [0 0 0 0 0 0 0 0 0 0]
Step 13: [0 0 0 0 0 0 0 0 0 0]
Step 14: [0 0 0 0 0 0 0 0 0 0]
Step 15: [0 0 0 0 0 0 0 0 0 0]
Step 16: [0 0 0 0 0 0 0 0 0 0]
Step 17: [0 0 0 0 0 0 0 0 0 0]
Step 18: [0 0 0 0 0 0 0 0 0 0]
Step 19: [0 0 0 0 0 0 0 0 0 0]
Step 20: [0 0 0 0 0 0 0 0 0 0]
Step 21: [0 0 0 0 0 0 0 0 0 0]
Step 22: [0 0 0 0 0 0 0 0 0 0]
Step 23: [0 0 0 0 0 0 0 0 0 0]
Step 24: [0 0 0 0 0 0 0 0 0 0]
Step 25: [0 0 0 0 0 0 0 0 0 0]
Step 26: [0 0 0 0 0 0 0 0 0 0]
Step 27: [0 0 0 0 0 0 0 0 0 0]
Step 28: [0 0 0 0 0 0 0 0 0 0]
Step 29: [0 0 0 0 0 0 0 0 0 0]
Step 30: [0 0 0 0 0 0 0 0 0 0]
Step 31: [0 0 0 0 0 0 0 0 0 0]
Step 32:

In [ ]:
# def temporalize(data, lookback):
#     output_data = []
#     for i in range(data.shape[1]):
#         column = data[:, i]
#         temp_column = []
#         for j in range(lookback, len(column)):
#             step = column[j-lookback:j]
#             if all(value == 0 for value in step):
#                 temp_column.append([0])
#             elif all(value == 1 for value in step):
#                 temp_column.append([1])
#             else:

#                 temp_column.append(None)
#         output_data.append(temp_column)
#     return output_data
# lookback = 10

# y_label = temporalize(labeled_values_array, lookback)

# for i, column in enumerate(y_label):
#     print(f"Column {i+1}:")
#     for j, step in enumerate(column):
#         print(f" {step}")
#     print()


In [ ]:
import numpy as np
import pandas as pd

def temporalize(data, lookback):
    output_data = []
    # Iterate over each column in the data
    for i in range(data.shape[1]):
        column = data[:, i]
        temp_column = []
        # Create temporalized sequences for the current column
        for j in range(lookback, len(column)):
            temp_column.append(column[j-lookback:j])
        output_data.append(temp_column)
    return output_data

# Assuming labeled_values is a pandas DataFrame
labeled_values_array = labeled_values.values
lookback = 10
# Temporalize the data
y_label = temporalize(labeled_values_array, lookback)

# Print the temporalized data
for i, column in enumerate(y_label):
    print(f"Column {i+1}:")
    for j, step in enumerate(column):
        print(f" {step}")
    print()


Column 1:
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 

In [ ]:
# Constructing X with only statistical values
X = []
for column in temporalized_data:
    for stats in column:
        X.append(stats)

# Printing X in the specified format
print("X = [")
for stats in X:
    print(stats)
print("]")



X = [
[-0.005400000000000027, 0.0, -0.028999999999999915, 0.0039999999999995595, 0.0, 0.010992724866928764, 0.00875999999999973, 0.00012083999999999403, 0.00875999999999973, 0.00719999999999974]
[-0.0019999999999999575, 0.0004999999999997229, -0.023999999999999133, 0.005000000000000782, 0.0, 0.008024961059095288, 0.00559999999999981, 6.439999999999576e-05, 0.00559999999999981, 0.004799999999999827]
[0.0026999999999999247, 0.0014999999999991687, -0.006999999999999673, 0.022999999999999687, 0.0, 0.007510659092250075, 0.004780000000000051, 5.640999999999872e-05, 0.004780000000000051, 0.004499999999999993]
[0.0035999999999999587, 0.0019999999999997797, -0.0030000000000001137, 0.022999999999999687, 0.0, 0.006799999999999952, 0.00424000000000003, 4.623999999999935e-05, 0.00424000000000003, 0.003600000000000314]
[0.004099999999999859, 0.002000000000000668, -0.0030000000000001137, 0.022999999999999687, 0.002000000000000668, 0.0066999999999999395, 0.004139999999999979, 4.4889999999999186e-05, 0

In [ ]:
#concatenate data
y = [step for column in y_label for step in column]

print("y = ", end="")
for i, step in enumerate(y_label):
    if i == 0:
        print("[", end="")
    print(step, end="")
    if i < len(y_label) - 1:
        print(", ", end="")
    else:
        print("]", end="")

y = [[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 

In [ ]:

X = np.array(X)
y = np.array(y)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (1076, 10)
Shape of y: (1076, 10)


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.array(X)
y = np.array(y)

trainX, testX, trainY, testY = train_test_split(X, y, test_size=1/3, random_state=42)

print("X_train shape:", trainX.shape)
print("X_test shape:", testX.shape)
print("y_train shape:", trainY.shape)
print("y_test shape:", testY.shape)


X_train shape: (717, 10)
X_test shape: (359, 10)
y_train shape: (717, 10)
y_test shape: (359, 10)


In [ ]:
print("TrainX shape:", trainX)
print("testX shape:", testX)
print("Trainy shape:", trainY)
print("Testy shape:", testY)


TrainX shape: [[ 3.000e-04  0.000e+00  0.000e+00 ...  2.100e-07  4.200e-04  3.000e-04]
 [-1.000e-04 -5.000e-04 -3.000e-03 ...  1.329e-05  2.300e-03  2.300e-03]
 [ 0.000e+00  0.000e+00 -1.000e-03 ...  2.000e-07  2.000e-04  2.000e-04]
 ...
 [-2.000e-04  0.000e+00 -3.000e-03 ...  2.560e-06  1.280e-03  1.200e-03]
 [ 6.000e-04  5.000e-04 -1.000e-03 ...  1.440e-06  1.000e-03  1.000e-03]
 [ 1.200e-03  1.000e-03  0.000e+00 ...  5.600e-07  5.200e-04  4.000e-04]]
testX shape: [[ 5.00e-04  5.00e-04 -2.00e-03 ...  1.85e-06  1.10e-03  1.10e-03]
 [-1.10e-03 -1.00e-03 -3.00e-03 ...  1.29e-06  9.40e-04  9.00e-04]
 [-2.00e-04  0.00e+00 -1.00e-03 ...  3.60e-07  4.80e-04  4.00e-04]
 ...
 [ 1.00e-04  0.00e+00 -1.00e-03 ...  2.90e-07  3.60e-04  3.00e-04]
 [-3.00e-04  0.00e+00 -3.00e-03 ...  1.21e-06  8.20e-04  7.00e-04]
 [-4.00e-04  0.00e+00 -4.00e-03 ...  4.04e-06  1.48e-03  1.40e-03]]
Trainy shape: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 [1 1 1

In [ ]:
print(trainY[:-10])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:

import numpy as np
from keras.models import Model
from keras.layers import Input, LSTM, Dense, RepeatVector, TimeDistributed, Dropout
from keras.models import Sequential

timesteps = 10
n_features = 1

input_shape = (timesteps, n_features)

autoencoder = Sequential([
    Input(shape=input_shape),
    LSTM(64, return_sequences=True),
    LSTM(32, return_sequences=True),
    LSTM(64, return_sequences=True),
    Dense(n_features, activation='sigmoid')
])

autoencoder.compile(optimizer='adam', loss='mean_squared_error')

autoencoder.fit(trainX, trainX, epochs=10, batch_size=32, validation_split=1/3)

encoder = Model(inputs=autoencoder.input, outputs=autoencoder.layers[2].output)

classification_model = Sequential([
    encoder,
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

classification_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

classification_model.fit(trainX, trainY, epochs=10, batch_size=32, validation_split=1/3)

predictions = classification_model.predict(testX)

binary_predictions = np.round(predictions).astype(int)

print("Predicted binary values:", binary_predictions)



Epoch 1/10
15/15 [==============================] - 13s 107ms/step - loss: 0.2249 - val_loss: 0.1728
Epoch 2/10
15/15 [==============================] - 0s 20ms/step - loss: 0.1041 - val_loss: 0.0571
Epoch 3/10
15/15 [==============================] - 0s 20ms/step - loss: 0.0443 - val_loss: 0.0346
Epoch 4/10
15/15 [==============================] - 0s 19ms/step - loss: 0.0300 - val_loss: 0.0260
Epoch 5/10
15/15 [==============================] - 0s 21ms/step - loss: 0.0234 - val_loss: 0.0208
Epoch 6/10
15/15 [==============================] - 0s 21ms/step - loss: 0.0189 - val_loss: 0.0170
Epoch 7/10
15/15 [==============================] - 0s 19ms/step - loss: 0.0156 - val_loss: 0.0143
Epoch 8/10
15/15 [==============================] - 0s 21ms/step - loss: 0.0133 - val_loss: 0.0123
Epoch 9/10
15/15 [==============================] - 0s 19ms/step - loss: 0.0115 - val_loss: 0.0106
Epoch 10/10
15/15 [==============================] - 0s 19ms/step - loss: 0.0098 - val_loss: 0.0089
Epoch 1

In [ ]:
print(binary_predictions[:50])

[[[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]
  [0]]

 [[0]
  

In [ ]:
# import numpy as np
# from keras.models import Model
# from keras.layers import Input, LSTM, Dense, RepeatVector, TimeDistributed, Dropout
# from keras.models import Sequential

# # Define input parameters
# num_features = 5  # Number of input features (min, max, mean, median, mode)
# input_shape = (num_features,)
# encoded_dim = 64  # Dimension of the encoded features

# # Define input layer
# inputs = Input(shape=input_shape)

# # Define encoder
# encoder = LSTM(encoded_dim, activation='relu')(inputs)

# # Define decoder
# decoder = RepeatVector(1)(encoder)
# decoder = LSTM(encoded_dim, activation='relu', return_sequences=True)(decoder)
# decoder = TimeDistributed(Dense(num_features))(decoder)

# # Define the autoencoder model
# autoencoder = Model(inputs, decoder)
# autoencoder.compile(optimizer='adam', loss='mse')

# # Train the autoencoder
# autoencoder.fit(X_train, X_train, epochs=10, batch_size=32, validation_split=0.2)

# # Extract the encoded features
# encoder = Model(inputs, encoder)
# encoded_features = encoder.predict(X_train)
# encoded_features_val = encoder.predict(X_val)
# encoded_features_test = encoder.predict(X_test)

# # Build the classification model
# classifier = Sequential()
# classifier.add(Dense(encoded_dim, activation='relu', input_dim=encoded_dim))
# classifier.add(Dropout(0.5))
# classifier.add(Dense(1, activation='sigmoid'))

# # Compile the classification model
# classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# # Train the classification model
# classifier.fit(encoded_features, y_train, epochs=100, batch_size=32, validation_data=(encoded_features_val, y_val))

# # Get predicted binary values for the test set
# y_pred = (classifier.predict(encoded_features_test) > 0.5).astype(int)

# # Print the predicted binary values
# print("Predicted Binary Values:")
# print(y_pred)

In [ ]:
# import numpy as np
# from keras.models import Model
# from keras.layers import Input, LSTM, Dense, RepeatVector, TimeDistributed

# timesteps = 10
# n_features = 1

# # Define the input layer
# visible = Input(shape=(timesteps, n_features))

# # Encoder
# encoder = LSTM(32, activation='relu', return_sequences=True)(visible)
# encoder = LSTM(16, activation='relu', return_sequences=False)(encoder)

# # Decoder for sequence prediction
# decoder1 = RepeatVector(timesteps)(encoder)
# decoder1 = LSTM(16, activation='relu', return_sequences=True)(decoder1)
# decoder1 = LSTM(32, activation='relu', return_sequences=True)(decoder1)
# decoder1 = TimeDistributed(Dense(100, activation='relu'))(decoder1)
# decoder1 = TimeDistributed(Dense(n_features), name='sequence_output')(decoder1)

# # Decoder for binary classification
# decoder2 = Dense(1, activation='sigmoid', name='classification_output')(encoder)

# # Define the model with two outputs
# model = Model(inputs=visible, outputs=[decoder1, decoder2])

# # Compile the model with two loss functions
# model.compile(optimizer='adam',
#               loss={'sequence_output': 'mse', 'classification_output': 'binary_crossentropy'},
#               metrics={'classification_output': 'accuracy'})


# # Fit the model
# model.fit(X, [X, y], epochs=50, verbose=0)

# # Predict on new data

# y_predict_class = model.predict(X_test, verbose=0)

# print(y_predict_class)


In [ ]:
  print(f"Shape of y_predict: {np.array(y_predict[0]).shape}, {np.array(y_predict[1]).shape}")

NameError: name 'y_predict' is not defined